### ISSUE TITLE
Minor issues for 0.2.0

### ISSUE THREAD

**Issue by ischoegl** [microcombustion/ctwrap#28]
This is a running list of minor issues that should be taken care of:

- [x] Replace CTI/XML mechanisms by YAML mechanism
- [x] Fix #32 (same issue as #29)
- [x] Check/minimize dependencies (e.g. pandas, pytables) ... ensure that `environment.y ml` already satisfies everything.
- [x] Issue #26 ... not a good idea after all; improvements of docstrings take care of this
- [x] ~Remove `output` from YAML configuration (it will always be HDF)~ ... enable passing of arguments to `write_hdf` (e.g. `force` overwriting of existing groups)
- [x] Include #36
- [x] Replace all instances of `io` by `pathlib`
- [x] Address `NaturalNameWarning`s (#1)
- [x] Include #35 (@ischoegl)
- [x] Include #42/#43 (@ischoegl)
- [x] Include #45 (@ischoegl)
- [x] Finish implementation of `Strategy`, I.e. #25 (@ischoegl)
- [x] Fix bug in #49
- [x] Bump version to `0.2.0`

Some remaining edits of Sphinx documentation

- [x] Move jupyter notebooks into a dedicated `docs/examples` folder (from current `docs/pages`) (@ischoegl ... see #45)
- [x] Add descriptions of how to run batch jobs from commandline to `overview.rst`, `ignition.rst` and `adiabatic_flame.rst` (see `README.rst`)
- [x] Check and fix broken links in Sphinx documentation (e.g. several links in `README.rst`)
- [x] Add instructions for conda environment to `INSTALL.rst` - see e.g. `camsym`
- [x] Update docstrings of `SimulationHandler` ... make description more generic (not tied to `minimal` example)

**Comment by ischoegl** [comment]
@DavidAkinpelu ... streamlined the code some more (there were some changes to `main`). I'm not planning to change anything else until you're done with the remaining items above.

**Comment by DavidAkinpelu** [comment]
Okay

**Comment by ischoegl** [comment]
@DavidAkinpelu  I'm done with my updates, so it's just documentation now.
